### PR TITLE
Support dynamic partition and ad-hoc cep runtime

### PR DESCRIPTION
**Pull request by wujinhu**
Add dynamic partition for dynamic added rules

Related Issue: #19 #2

### CODE REVIEW

**Comment by wujinhu** [comment]
@haoch  Please help to review this PR, thanks

**Comment by haoch** [comment]
@wujinhu Please keep the original API for backward compasibility and add some new API for multiple stream output.

**Comment by wujinhu** [comment]
@haoch OK, I have brought interfaces back and added new interfaces.

**Comment by haoch** [comment]
Use:
* `sink(outputStreamId)` for register outputStream callback
* `returnX()` without outputStreamId to return multiple stream like `DataStream<Tuple<String, T>>`

**Comment by haoch** [comment]
LGTM @wujinhu. Do you think it's ready to merge now?

**Pull request merged**
